"""
ARIA ESI Core Module

Shared infrastructure for ESI API access.
"""

from .auth import (
    Credentials,
    CredentialsError,
    get_authenticated_client,
    get_credential_storage_info,
    get_credentials,
    get_pilot_directory,
    is_player_corp,
    migrate_credentials_to_keyring,
)
from .client import ESIClient, ESIError
from .constants import (
    ACTIVITY_TYPES,
    CORP_SCOPES,
    ESI_BASE_URL,
    ESI_DATASOURCE,
    HIGH_SEC_THRESHOLD,
    INCOME_REF_TYPES,
    LOW_SEC_THRESHOLD,
    PLAYER_CORP_MIN_ID,
    REF_TYPE_CATEGORIES,
    REF_TYPE_NAMES,
    SHIP_GROUP_IDS,
    SLOT_ORDER,
    STATION_NAMES,
    TRADE_HUB_REGIONS,
    TRADE_HUB_STATIONS,
)
from .data_integrity import (
    IntegrityError,
    compute_sha256,
    get_eos_repository,
    get_integrity_status,
    get_pinned_eos_commit,
    get_pinned_sde_url,
    get_universe_graph_checksum,
    is_break_glass_enabled,
    load_data_manifest,
    update_universe_graph_checksum,
    verify_checksum,
    verify_eos_commit,
    verify_sde_integrity,
    verify_universe_graph_integrity,
)
from .formatters import (
    calculate_progress,
    format_datetime,
    format_duration,
    format_duration_long,
    format_eft_cargo,
    format_eft_drone,
    format_eft_header,
    format_isk,
    format_isk_full,
    format_progress,
    format_ref_type,
    format_security,
    format_skill_level,
    get_security_class,
    get_security_description,
    get_utc_now,
    get_utc_timestamp,
    parse_datetime,
    time_since,
    time_until,
    to_roman,
)
from .keyring_backend import (
    KEYRING_AVAILABLE,
    KEYRING_BACKEND,
    KeyringCredentialStore,
    delete_from_keyring,
    get_keyring_status,
    get_keyring_store,
    is_keyring_enabled,
    load_from_keyring,
    store_in_keyring,
)
from .logging import (
    debug_enabled,
    debug_log,
    get_logger,
    set_log_level,
)
from .path_security import (
    ALLOWED_EXTENSIONS,
    DEFAULT_MAX_FILE_SIZE,
    PERSONA_ALLOWED_PREFIXES,
    PILOT_ID_PATTERN,
    PathValidationError,
    safe_read_persona_file,
    validate_path,
    validate_persona_file_path,
    validate_persona_path,
    validate_pilot_id,
)
from .path_security import (
    is_break_glass_enabled as is_path_break_glass_enabled,
)
from .retry import (
    RETRYABLE_STATUS_CODES,
    TENACITY_AVAILABLE,
    NonRetryableESIError,
    RetryableESIError,
    esi_retry,
    get_retry_status,
    is_retry_enabled,
)

__all__ = [
    # Client
    "ESIClient",
    "ESIError",
    # Data Integrity
    "IntegrityError",
    "compute_sha256",
    "verify_checksum",
    "is_break_glass_enabled",
    "load_data_manifest",
    "get_pinned_sde_url",
    "verify_sde_integrity",
    "get_pinned_eos_commit",
    "get_eos_repository",
    "verify_eos_commit",
    "get_integrity_status",
    "get_universe_graph_checksum",
    "verify_universe_graph_integrity",
    "update_universe_graph_checksum",
    # Auth
    "Credentials",
    "CredentialsError",
    "get_credentials",
    "get_authenticated_client",
    "get_pilot_directory",
    "is_player_corp",
    "migrate_credentials_to_keyring",
    "get_credential_storage_info",
    # Keyring
    "KEYRING_AVAILABLE",
    "KEYRING_BACKEND",
    "is_keyring_enabled",
    "get_keyring_status",
    "KeyringCredentialStore",
    "get_keyring_store",
    "store_in_keyring",
    "load_from_keyring",
    "delete_from_keyring",
    # Retry
    "TENACITY_AVAILABLE",
    "is_retry_enabled",
    "get_retry_status",
    "esi_retry",
    "RetryableESIError",
    "NonRetryableESIError",
    "RETRYABLE_STATUS_CODES",
    # Formatters
    "format_isk",
    "format_isk_full",
    "format_duration",
    "format_duration_long",
    "to_roman",
    "format_skill_level",
    "parse_datetime",
    "format_datetime",
    "get_utc_now",
    "get_utc_timestamp",
    "time_until",
    "time_since",
    "format_security",
    "get_security_class",
    "get_security_description",
    "format_progress",
    "calculate_progress",
    "format_eft_header",
    "format_eft_drone",
    "format_eft_cargo",
    "format_ref_type",
    # Constants
    "ESI_BASE_URL",
    "ESI_DATASOURCE",
    "SHIP_GROUP_IDS",
    "TRADE_HUB_REGIONS",
    "TRADE_HUB_STATIONS",
    "STATION_NAMES",
    "ACTIVITY_TYPES",
    "REF_TYPE_CATEGORIES",
    "REF_TYPE_NAMES",
    "INCOME_REF_TYPES",
    "SLOT_ORDER",
    "HIGH_SEC_THRESHOLD",
    "LOW_SEC_THRESHOLD",
    "CORP_SCOPES",
    "PLAYER_CORP_MIN_ID",
    # Logging
    "get_logger",
    "set_log_level",
    "debug_enabled",
    "debug_log",
    # Path Security
    "PathValidationError",
    "validate_path",
    "validate_persona_path",
    "validate_persona_file_path",
    "safe_read_persona_file",
    "validate_pilot_id",
    "PERSONA_ALLOWED_PREFIXES",
    "PILOT_ID_PATTERN",
    "ALLOWED_EXTENSIONS",
    "DEFAULT_MAX_FILE_SIZE",
    "is_path_break_glass_enabled",
]
