# Rupture L2 Missions - Medium Skill Variant
#
# Solid mid-level fit for established pilots.
# T2 damage modules for improved DPS.

archetype:
  hull: Rupture
  skill_tier: meta
  omega_required: false

eft: |
  [Rupture, L2 Missions - Medium Skills]

  Gyrostabilizer II
  Gyrostabilizer II
  Damage Control II
  Medium Armor Repairer I
  Multispectrum Energized Membrane I

  50MN Microwarpdrive I
  Medium Compact Pb-Acid Cap Battery
  Tracking Computer I

  425mm AutoCannon I
  425mm AutoCannon I
  425mm AutoCannon I
  425mm AutoCannon I
  [Empty High slot]

  Medium Auxiliary Nano Pump I
  Medium Auxiliary Nano Pump I
  Medium Projectile Burst Aerator I

  Hobgoblin I x3
  Warrior I x3

  EMP M x2000
  Phased Plasma M x1000
  Fusion M x1000
  Titanium Sabot M x500
  Tracking Speed Script x1

skill_requirements:
  required:
    Minmatar Cruiser: 3
    Medium Projectile Turret: 4
    Gunnery: 4
    Repair Systems: 3
    Hull Upgrades: 3
    Weapon Upgrades: 4
  recommended:
    Motion Prediction: 4
    Surgical Strike: 3
    Rapid Firing: 3
    Mechanics: 4

stats:
  dps: 235
  ehp: 11000
  tank_sustained: 80
  capacitor_stable: true
  align_time: 8.0
  speed_mwd: 1450
  optimal_range: 2500
  falloff: 13000
  validated_date: "2026-01-24"

damage_tuning:
  default_damage: em_kinetic
  tank_profile: armor_active

  overrides:
    serpentis:
      ammo: "Phased Plasma M"
      drones:
        primary: "Hobgoblin I"
      notes: "Serpentis weak to Thermal"

    angel_cartel:
      ammo: "Fusion M"
      drones:
        primary: "Warrior I"
      notes: "Angels weak to Explosive"

    blood_raiders:
      ammo: "EMP M"
      drones:
        primary: "Acolyte I"
      notes: "Blood Raiders weak to EM - default ammo works"

    guristas:
      ammo: "Titanium Sabot M"
      drones:
        primary: "Hornet I"
      notes: "Guristas weak to Kinetic"

    rogue_drones:
      ammo: "EMP M"
      drones:
        primary: "Acolyte I"
      notes: "Drones weak to EM"

    mercenaries:
      ammo: "Phased Plasma M"
      drones:
        primary: "Hobgoblin I"
      notes: "Mercenaries weak to Thermal"

notes:
  purpose: "General-purpose L2 mission runner with moderate skills"
  engagement: "Close fast with MWD, orbit at 2-5km, swap ammo for target"
  warnings:
    - "T2 Gyrostabilizers significantly boost DPS"
    - "Swap ammo freely - no reload penalty"
    - "Guns use NO capacitor - very forgiving"

upgrade_path:
  next_tier: t2_optimal
  key_upgrades:
    - module: "425mm AutoCannon I"
      upgrade_to: "425mm AutoCannon II"
      skill_required: "Medium Projectile Turret 5"
    - module: "Medium Armor Repairer I"
      upgrade_to: "Medium Armor Repairer II"
      skill_required: "Repair Systems 5"
