# Home Defense - Staging System Alerts
#
# Monitors activity in and around your home base.
# Good for: Knowing when to stay docked, detecting hostile scouts
#
# Setup:
#   1. Copy to userdata/notifications/home-defense.yaml
#   2. Replace webhook_url with your Discord webhook
#   3. Replace systems with YOUR home system and adjacent systems
#   4. Add hostile corps/alliances to your watchlist

schema_version: 1

name: "home-defense"
display_name: "Home Defense"
description: "Activity alerts for home staging area"
enabled: true

# Replace with your Discord webhook URL
webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN"

topology:
  geographic:
    systems:
      # YOUR HOME SYSTEM - replace with actual home
      - name: "Stacmon"
        classification: "home"

      # Adjacent systems (1 jump) - your early warning network
      - name: "Covryn"
        classification: "transit"
      - name: "Ostingele"
        classification: "transit"
      - name: "Aulbres"
        classification: "transit"

      # Known hostile staging (optional) - watch for fleet formations
      # - name: "EnemyStaging"
      #   classification: "avoidance"

triggers:
  watchlist_activity: true        # Critical: alerts on war targets
  gatecamp_detected: true         # Know before you undock
  high_value_threshold: 0         # All kills matter near home

throttle_minutes: 5               # Balance awareness vs spam

quiet_hours:
  enabled: true
  start: "03:00"                  # Suppress during sleep hours
  end: "09:00"
  timezone: "America/New_York"    # Change to your timezone
