"""
Per-module coverage threshold enforcement.

Reads coverage.json (generated by pytest --cov-report=json) and checks
per-package thresholds defined in pyproject.toml [tool.aria.coverage_thresholds].

Exit code 0 = all pass, 1 = threshold violated.
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

# Try tomllib (3.11+), fall back to tomli
try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore[no-redef]


def load_thresholds(pyproject_path: Path) -> dict[str, float]:
    """Load per-module coverage thresholds from pyproject.toml."""
    with open(pyproject_path, "rb") as f:
        data = tomllib.load(f)
    return data.get("tool", {}).get("aria", {}).get("coverage_thresholds", {})


def aggregate_coverage(coverage_data: dict) -> dict[str, dict[str, int]]:
    """Aggregate file-level coverage data into per-package totals.

    Returns dict mapping module name to {stmts, miss, branches, branch_miss}.
    """
    modules: dict[str, dict[str, int]] = defaultdict(
        lambda: {"stmts": 0, "miss": 0, "branches": 0, "branch_miss": 0}
    )

    for fpath, fdata in coverage_data.get("files", {}).items():
        if not fpath.startswith("src/aria_esi/"):
            continue
        rel = fpath[len("src/aria_esi/") :]
        parts = rel.split("/")

        # Two-level grouping for services/* and mcp/*
        if parts[0] in ("services", "mcp", "store") and len(parts) > 1:
            mod = f"{parts[0]}/{parts[1]}"
        else:
            mod = parts[0].replace(".py", "")

        s = fdata["summary"]
        modules[mod]["stmts"] += s["num_statements"]
        modules[mod]["miss"] += s["missing_lines"]
        modules[mod]["branches"] += s["num_branches"]
        modules[mod]["branch_miss"] += s["missing_branches"]

    return dict(modules)


def calculate_coverage_pct(mod_data: dict[str, int]) -> float:
    """Calculate coverage percentage from aggregated module data."""
    total = mod_data["stmts"] + mod_data["branches"]
    if total == 0:
        return 100.0
    missed = mod_data["miss"] + mod_data["branch_miss"]
    return (total - missed) / total * 100


def check_thresholds(
    thresholds: dict[str, float],
    modules: dict[str, dict[str, int]],
) -> list[tuple[str, float, float]]:
    """Check each threshold against actual coverage.

    Returns list of (module, actual_pct, threshold_pct) for failures.
    """
    failures = []
    for mod, threshold in sorted(thresholds.items()):
        if mod not in modules:
            continue
        actual = calculate_coverage_pct(modules[mod])
        if actual < threshold:
            failures.append((mod, actual, threshold))
    return failures


def main() -> int:
    project_root = Path(__file__).resolve().parent.parent.parent
    coverage_path = project_root / "coverage.json"
    pyproject_path = project_root / "pyproject.toml"

    if not coverage_path.exists():
        print("ERROR: coverage.json not found. Run pytest with --cov-report=json first.")
        return 1

    if not pyproject_path.exists():
        print("ERROR: pyproject.toml not found.")
        return 1

    thresholds = load_thresholds(pyproject_path)
    if not thresholds:
        print("No coverage thresholds defined in [tool.aria.coverage_thresholds].")
        return 0

    with open(coverage_path) as f:
        coverage_data = json.load(f)

    modules = aggregate_coverage(coverage_data)

    # Print table
    print(f"\n{'Module':<30} {'Actual':>7} {'Threshold':>10} {'Status':>8}")
    print("-" * 60)

    for mod, threshold in sorted(thresholds.items()):
        if mod not in modules:
            print(f"{mod:<30} {'N/A':>7} {threshold:>9.1f}% {'SKIP':>8}")
            continue
        actual = calculate_coverage_pct(modules[mod])
        status = "OK" if actual >= threshold else "FAIL"
        print(f"{mod:<30} {actual:>6.1f}% {threshold:>9.1f}% {status:>8}")

    failures = check_thresholds(thresholds, modules)

    print()
    if failures:
        print(f"FAILED: {len(failures)} module(s) below threshold:")
        for mod, actual, threshold in failures:
            print(f"  {mod}: {actual:.1f}% < {threshold:.1f}%")
        return 1

    print("All module coverage thresholds passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
